name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: 0.10.0  # Replace with your desired Zig version

    - name: Build Project
      run: make
